config/routes.rb
Rails.application.routes.draw do

  root 'users#new'

  resources :pictures do 
    collection do
      post :confirm
    end
  end
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :favorites, only: [:create, :destroy, :index]

  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  
  mount_uploader :image, ImageUploader

  validates :content, presence: true
  
  belongs_to :user
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/user.rb
class User < ApplicationRecord

  mount_uploader :image, ProfileImageUploader
  
  before_validation { email.downcase!}
  has_secure_password

  validates :password, length: { minimum: 6 }, on: :create
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  has_many :pictures
  has_many :favorites, dependent: :destroy
  has_many :favorite_picture, through: :favorites, source: :picture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required

  private

  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
    @favorites = current_user.favorites
  end

  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_path
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_path
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  before_action :set_picture, only: %i[ show edit update destroy ]
  before_action :ensure_current_user, only: %i[ edit update destroy ]

  def index
    @pictures = Picture.all.order("created_at DESC").where.not(image: nil)
    @favorite = current_user.favorites.find_by(params[:id])
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  def edit
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    render :new and return if params[:back]
    if @picture.save
      ContactMailer.contact_mail(@picture).deliver
      redirect_to pictures_path
    else
      render :new
    end
  end

  def confirm
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end

  def update
    if @picture.update(picture_params)
      redirect_to pictures_url
    else
      render :edit
    end
  end

  def destroy
    @picture.destroy
    redirect_to pictures_url
  end

  private
  
  def set_picture
    @picture = Picture.find(params[:id])
  end

  def picture_params
    params.require(:picture).permit(:image, :image_cache, :content, :user_id)
  end

  def ensure_current_user
    unless @picture.user == current_user
      flash[:notice]="you don't have authority"
      redirect_to pictures_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to pictures_path(user.id)
    else
      flash.now[:danger] = 'failed to log in'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'logged out'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :login_required, only: %i[ new create ]
  before_action :set_user, only: %i[ show edit update ]
  before_action :ensure_current_user, only: %i[ edit update ]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:image, :name, :profile, :email, :password, :password_confirmation)
  end

  def ensure_current_user
    unless @user == current_user
      flash[:notice]="you don't have authority"
      redirect_to pictures_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<article>
<% @favorites.each do |favorite| %>
  <div class="post">
    <div class="profileFlex">
      <p><%= image_tag favorite.picture.user.image.url if favorite.picture.user.image.present? %></p>
      <p><%= favorite.picture.user.name %></p>
    </div>
    <p><%= image_tag favorite.picture.image.url if favorite.picture.image.present? %></p>
    <p><%= favorite.picture.content %></p>

    <div class="menuFlex">
      <p><%= link_to 'Show', picture_path(favorite.picture.id) %></p>
      <% unless favorite.picture.user_id == current_user.id %>
        <% if favorite.present? %>
          <p><%= link_to 'unlike', favorite_path(id: favorite.id), method: :delete %></p>
        <% else %>
          <p><%= link_to 'like', favorites_path(picture_id: favorite.picture.id), method: :post %></p>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramCloneApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="innerWrap">
        <h1>instagram</h1>
        <div class="menu">
          <% unless logged_in? %>
            <%= link_to "Sign up", new_user_path %>
            <%= link_to "Login", new_session_path %>
          <% end %>
        </div>
      </div>
    </header>
    <main class="container">
      <div class="innerWrap">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "#{key}") %>
        <% end %>
        <%= yield %>
        <% if logged_in? %>
          <nav>
            <p><%= link_to image_tag("home_icon.png"), pictures_path %></p>
            <p><%= link_to image_tag("post_icon.png"), new_picture_path %></p>
            <p><%= link_to image_tag("profile_icon.png"), user_path(current_user.id) %></p>
          </nav>
        <% end %>
      </div>
    </main>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture, local: true, url: choose_new_or_edit) do |form| %>

  <div class="field">
    <%= form.label :image %>
    <%= image_tag(picture.image.url) if picture.image && picture.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, size: "55x10" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pictures/confirm.html.erb
<h3>send as below</h3>

<%= form_with(model: @picture, local: true) do |f| %>
  <p><%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %></p>
  <%= f.hidden_field :image_cache %>

  <p>content: <%= @picture.content %></p>
  <%= f.hidden_field :content%>

  <%= f.submit "submit" %>
<% end %>

<%= form_with(model:@picture, local: true, url: new_picture_path, method: "get", class: "confirmBackButton") do |f| %>
  <%= f.hidden_field :image_cache %>
  <%= f.submit "back", name: 'back' %>
<% end%>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<article>
  <% @pictures.each do |picture| %>
    <div class="post">
      <div class="profileFlex">
        <p><%= link_to image_tag(picture.user.image.url), user_path(picture.user.id) if picture.user.image.present? %></p>
        <p><%= picture.user.name %></p>
      </div>
      <p><%= image_tag picture.image.url if picture.image.present? %></p>
      <p><%= picture.content %></p>

      <div class="menuFlex">
          <p><%= link_to 'Show', picture %></p>
      </div>
    </div>
  <% end %>
</article>

app/views/pictures/new.html.erb
<h1>New Picture</h1>
<% if @picture.errors.any? %>
  <div id="error_explanation">
    <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
    <ul>
    <% @picture.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= render 'form', picture: @picture %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p>
  <%= @picture.user.name %>
</p>

<p>
  <%= image_tag @picture.image.url if @picture.image.present? %>
</p>

<p>
  <%= @picture.content %>
</p>

<% unless @picture.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'unlike', favorite_path(id: @favorite.id), method: :delete %>
  <% else %>
    <%= link_to 'like', favorites_path(picture_id: @picture.id), method: :post %>
  <% end %>
<% end %>

<% if @picture.user_id == current_user.id %>
  <p><%= link_to 'edit', edit_picture_path(@picture) %></p>
  <p><%= link_to 'Destroy', @picture, method: :delete, data: { confirm: 'Are you sure?' } %></p>
<% end %>
<%= link_to 'Back', pictures_path %>

app/views/users/edit.html.erb
<h1>Profile</h1>

<%= form_with(model: @user, local: true) do |f| %>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>

  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_area :name %>
  </div>

  <div class="field">
    <%= f.label :profile %>
    <%= f.text_area :profile %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_area :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <div class="form_innerWrap">
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :image %>
      <%= f.file_field :image %>
    </div>

    <div class="field">
      <%=f.label :email %>
      <%= f.email_field :email %>
    </div>

    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>

    <div class="signUpButton">
      <%= f.submit "create my account" %>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="myPageLinks">
    <p><%= link_to 'Favorites', favorites_path %></p>
  <% if @user.id == current_user.id %>
    <p><%= link_to 'Edit Profile', edit_user_path(@user) %></p>
    <p><%= link_to "Logout", session_path(current_user.id), method: :delete %></p>
  <% end %>
</div>

<div class="profile">
  <p><%= image_tag @user.image.url if @user.image.present? %></p>
  <p><%= @user.name %></p>
  <p><%= @user.profile %></p>
</div>

<article class="myPosts">
  <% @user.pictures.each do |picture| %>
    <div class="post">
      <div class="profileFlex">
        <p><%= image_tag picture.user.image.url if @user.image.present? %></p>
        <p><%= picture.user.name %></p>
      </div>
      <p><%= image_tag picture.image.url if picture.image.present? %></p>
      <p><%= picture.content %></p>

      <div class="menuFlex">
        <p><%=link_to 'show', picture %></p>
      <% if picture.user_id == current_user.id %>
        <p><%= link_to 'edit', edit_picture_path(picture) %></p>
        <p><%= link_to 'destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></p>
      <% end %>
        <p></p>
      </div>
    </div>
  <% end %>
</article>